FROM cassandra:{{CASSANDRA_VER}}

ENV AXON_AGENT_LOG_OUTPUT=std

RUN AGENT_VER=$(echo "$CASSANDRA_VERSION" | sed -r 's/^([0-9]+\.[0-9]+).*$/\1/') && \
    groupadd --gid 9988 axonops && \
    useradd --gid 9988 --uid 9988 --shell /bin/bash -c "AxonOps" -G cassandra axonops && \
    usermod -aG axonops cassandra && \
    apt-get -y update && apt-get -y install curl gnupg netcat-openbsd && \
    curl https://packages.axonops.com/apt/repo-signing-key.gpg | apt-key add - && \
    echo "deb https://packages.axonops.com/apt axonops-apt main" >/etc/apt/sources.list.d/axonops-apt.list && \
    apt-get -y update && \
    if [ "$AGENT_VER" = "5.0" ]; then apt-get -y install axon-cassandra${AGENT_VER}-agent-jdk17; else apt-get -y install axon-cassandra${AGENT_VER}-agent; fi && \
    apt-get -y clean && \
    echo 'axon-agent:' > /etc/axonops/axon-agent.yml && \
    chown cassandra:cassandra /etc/axonops/axon-agent.yml && \
    chmod 0400 /etc/axonops/axon-agent.yml && \
    touch /var/run/utmp

COPY axonops-entrypoint.sh /axonops-entrypoint.sh
RUN chown root:root /axonops-entrypoint.sh && chmod 0755 /axonops-entrypoint.sh

ENTRYPOINT ["/axonops-entrypoint.sh"]
CMD ["cassandra", "-f"]
